CREATE TABLE IF NOT EXISTS DOCTORS (
    id SERIAL PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    email VARCHAR(250) NOT NULL,
    speciality VARCHAR(250) NOT NULL,
    password VARCHAR(250) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    hospital VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS PATIENTS (
    id SERIAL PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    email VARCHAR(250) NOT NULL,
    password VARCHAR(250) NOT NULL,
    phone VARCHAR(50) NOT NULL
);